import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, Paper, InputBase, IconButton } from "@mui/material/";
import SearchIcon from "@mui/icons-material/Search";
import { useForm, Controller } from "react-hook-form";
import { useRouter } from "next/router";
import { height } from "@mui/system";

export default function Home() {

  const router = useRouter();

  const { control, handleSubmit } = useForm({
    defaultValues: {
      search: "",
    },
  });

  const onSubmit = (data) => {
    
    if (data.search == "") {
      router.push(`/results?q=all`);
    } else {
      router.push(`/results?q=${data.search}`);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Une</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Box sx={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "center",
          height: "95vh"
        }}>

      
        <h1 className={styles.title}>UNE</h1>
        <Paper
          component="form"
          onSubmit={handleSubmit(onSubmit)}
          sx={{
            p: "2px 4px",
            display: "flex",
            alignItems: "center",
            width: 400,
          }}
        >
          <Controller
            name="search"
            control={control}
            render={({ field }) => (
              <InputBase
                {...field}
                sx={{ ml: 1, flex: 1 }}
                placeholder="Faça uma busca"
                inputProps={{ "aria-label": "Faça uma busca" }}
              />
            )}
          />
          <IconButton type="submit" sx={{ p: "10px" }} aria-label="search">
            <SearchIcon />
          </IconButton>
        </Paper>
        </Box>
    </div>
  );
}
